### ISSUE TITLE
Show user name at bottom left corner of video at all times

### ISSUE THREAD

**Issue by samandmoore** [kfinn/casual_rails#22]
I think it'd be nice to show the user name at all times instead of just when hovering a video box

**Comment by kfinn** [comment]
Interesting!

I guess I'm imagining this tool for primarily people who already know each other, where like if we were in real life we wouldn't use name tags. Maybe that's a bad comparison though.

I know in my online board game implementations, everyone I know trolls each other with fake names, so I kind of assumed they'd be a distraction here too. I tried not building names at all, but it was hard to test features on my own without naming the streams

**Comment by samandmoore** [comment]
Yea I guess it's most annoying to me when doing development, but I also think that when someone turns off their video it's nice to be able to know which box is which. So maybe I'd be satisfied with always showing the name when video is off
