### ISSUE TITLE
rethink twilio room creation

### ISSUE THREAD

**Issue by kfinn** [kfinn/casual_rails#25]
empty twilio rooms only stick around for 5 minutes, so there's a very common dev flow that results in a failure...

- click "create room"
- wait 6 mins
- click "join room"
- stare at black screen 💔

**Comment by samandmoore** [comment]
I think we also wanna consider that rooms expire after 24 hours and folks can only be connected for 4 hours. Also the room expires after everyone is disconnected for 5 minutes. 

So, we might wanna introduce some health check on the server side for the room and then maybe we can tell clients go reconnect or something. Like a reset of the room state almost like a page refresh.
