### ISSUE TITLE
naming tech debt

### ISSUE THREAD

**Issue by kfinn** [kfinn/casual_rails#27]
I sure picked some misleading names for `twilioRemoteParticipant` and `remoteParticipant` and `TwilioRemoteParticipantSnapshot`

**Comment by samandmoore** [comment]
made some improvements here by renaming a buncha `twilioRemoteParticipant` things to `remoteMembership` but i think we need to do a bigger sweep that uses `membershipId` in more places instead of `twilioParticipantSid`

**Comment by samandmoore** [comment]
soooo closed! #31
